# Generated by Django 5.2.7 on 2025-10-07 18:15

import django.core.validators
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Autor',
            fields=[
                ('id_autor', models.CharField(max_length=5, primary_key=True, serialize=False, validators=[django.core.validators.RegexValidator('^[A-Z0-9]+$', 'Solo se permiten letras mayúsculas y números.')])),
                ('nombre', models.CharField(max_length=100)),
                ('nacionalidad', models.CharField(blank=True, max_length=50, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Carrera',
            fields=[
                ('id_carrera', models.CharField(max_length=5, primary_key=True, serialize=False, validators=[django.core.validators.RegexValidator('^[A-Z0-9]+$', 'Solo se permiten letras mayúsculas y números.')])),
                ('nombre', models.CharField(max_length=50, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='Categoria',
            fields=[
                ('id_categoria', models.CharField(max_length=5, primary_key=True, serialize=False, validators=[django.core.validators.RegexValidator('^[A-Z0-9]+$', 'Solo se permiten letras mayúsculas y números.')])),
                ('nombre', models.CharField(max_length=50, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='Editorial',
            fields=[
                ('id_editorial', models.CharField(max_length=5, primary_key=True, serialize=False, validators=[django.core.validators.RegexValidator('^[A-Z0-9]+$', 'Solo se permiten letras mayúsculas y números.')])),
                ('nombre', models.CharField(max_length=50)),
                ('pais', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='Usuario',
            fields=[
                ('id_usuario', models.CharField(max_length=5, primary_key=True, serialize=False, validators=[django.core.validators.RegexValidator('^[A-Z0-9]+$', 'Solo se permiten letras mayúsculas y números.')])),
                ('nombre', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Alumno',
            fields=[
                ('id_alumno', models.CharField(max_length=5, primary_key=True, serialize=False, validators=[django.core.validators.RegexValidator('^[A-Z0-9]+$', 'Solo se permiten letras mayúsculas y números.')])),
                ('nombre', models.CharField(max_length=100)),
                ('semestre', models.IntegerField(validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(12)])),
                ('carrera', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='biblioteca.carrera')),
            ],
        ),
        migrations.CreateModel(
            name='Libro',
            fields=[
                ('id_libro', models.CharField(max_length=5, primary_key=True, serialize=False, validators=[django.core.validators.RegexValidator('^[A-Z0-9]+$', 'Solo se permiten letras mayúsculas y números.')])),
                ('titulo', models.CharField(max_length=100)),
                ('anio_publicacion', models.CharField(max_length=4, validators=[django.core.validators.RegexValidator('^\\d{4}$', 'Debe ser un año de 4 dígitos.')])),
                ('autor', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='biblioteca.autor')),
                ('categoria', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='biblioteca.categoria')),
                ('editorial', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='biblioteca.editorial')),
            ],
        ),
        migrations.CreateModel(
            name='Sancion',
            fields=[
                ('id_sancion', models.CharField(max_length=5, primary_key=True, serialize=False, validators=[django.core.validators.RegexValidator('^[A-Z0-9]+$', 'Solo se permiten letras mayúsculas y números.')])),
                ('motivo', models.CharField(max_length=100)),
                ('fecha', models.DateField()),
                ('fecha_fin', models.DateField(blank=True, null=True)),
                ('alumno', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='biblioteca.alumno')),
            ],
        ),
        migrations.CreateModel(
            name='Prestamo',
            fields=[
                ('id_prestamo', models.CharField(max_length=5, primary_key=True, serialize=False, validators=[django.core.validators.RegexValidator('^[A-Z0-9]+$', 'Solo se permiten letras mayúsculas y números.')])),
                ('fecha_prestamo', models.DateField()),
                ('fecha_devolucion', models.DateField()),
                ('alumno', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='biblioteca.alumno')),
                ('libro', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='biblioteca.libro')),
                ('usuario', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='biblioteca.usuario')),
            ],
        ),
        migrations.CreateModel(
            name='Historial',
            fields=[
                ('id_historial', models.CharField(max_length=5, primary_key=True, serialize=False, validators=[django.core.validators.RegexValidator('^[A-Z0-9]+$', 'Solo se permiten letras mayúsculas y números.')])),
                ('fecha_prestamo', models.DateField()),
                ('fecha_devolucion', models.DateField(blank=True, null=True)),
                ('alumno', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='biblioteca.alumno')),
                ('libro', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='biblioteca.libro')),
                ('usuario', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='biblioteca.usuario')),
            ],
        ),
    ]
