# Generated by Django 5.2.7 on 2025-10-28 03:38

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('biblioteca', '0003_alter_alumno_nombre_alter_autor_nacionalidad_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='alumno',
            name='id_alumno',
            field=models.CharField(max_length=10, primary_key=True, serialize=False, validators=[django.core.validators.RegexValidator('^[A-Z0-9]+$', 'Solo se permiten letras mayúsculas y números.')]),
        ),
        migrations.AlterField(
            model_name='alumno',
            name='nombre',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='alumno',
            name='semestre',
            field=models.IntegerField(validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(12)]),
        ),
        migrations.AlterField(
            model_name='autor',
            name='id_autor',
            field=models.CharField(max_length=10, primary_key=True, serialize=False, validators=[django.core.validators.RegexValidator('^[A-Z0-9]+$', 'Solo se permiten letras mayúsculas y números.')]),
        ),
        migrations.AlterField(
            model_name='autor',
            name='nacionalidad',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='autor',
            name='nombre',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='carrera',
            name='id_carrera',
            field=models.CharField(max_length=10, primary_key=True, serialize=False, validators=[django.core.validators.RegexValidator('^[A-Z0-9]+$', 'Solo se permiten letras mayúsculas y números.')]),
        ),
        migrations.AlterField(
            model_name='categoria',
            name='id_categoria',
            field=models.CharField(max_length=10, primary_key=True, serialize=False, validators=[django.core.validators.RegexValidator('^[A-Z0-9]+$', 'Solo se permiten letras mayúsculas y números.')]),
        ),
        migrations.AlterField(
            model_name='editorial',
            name='id_editorial',
            field=models.CharField(max_length=10, primary_key=True, serialize=False, validators=[django.core.validators.RegexValidator('^[A-Z0-9]+$', 'Solo se permiten letras mayúsculas y números.')]),
        ),
        migrations.AlterField(
            model_name='editorial',
            name='pais',
            field=models.CharField(max_length=50),
        ),
        migrations.AlterField(
            model_name='historial',
            name='id_historial',
            field=models.CharField(max_length=10, primary_key=True, serialize=False, validators=[django.core.validators.RegexValidator('^[A-Z0-9]+$', 'Solo se permiten letras mayúsculas y números.')]),
        ),
        migrations.AlterField(
            model_name='libro',
            name='id_libro',
            field=models.CharField(max_length=10, primary_key=True, serialize=False, validators=[django.core.validators.RegexValidator('^[A-Z0-9]+$', 'Solo se permiten letras mayúsculas y números.')]),
        ),
        migrations.AlterField(
            model_name='libro',
            name='titulo',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='prestamo',
            name='id_prestamo',
            field=models.CharField(max_length=10, primary_key=True, serialize=False, validators=[django.core.validators.RegexValidator('^[A-Z0-9]+$', 'Solo se permiten letras mayúsculas y números.')]),
        ),
        migrations.AlterField(
            model_name='sancion',
            name='id_sancion',
            field=models.CharField(max_length=10, primary_key=True, serialize=False, validators=[django.core.validators.RegexValidator('^[A-Z0-9]+$', 'Solo se permiten letras mayúsculas y números.')]),
        ),
        migrations.AlterField(
            model_name='usuario',
            name='id_usuario',
            field=models.CharField(max_length=10, primary_key=True, serialize=False, validators=[django.core.validators.RegexValidator('^[A-Z0-9]+$', 'Solo se permiten letras mayúsculas y números.')]),
        ),
        migrations.AlterField(
            model_name='usuario',
            name='nombre',
            field=models.CharField(max_length=100),
        ),
    ]
