# Generated by Django 5.2.7 on 2025-10-28 03:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('biblioteca', '0004_alter_alumno_id_alumno_alter_alumno_nombre_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='alumno',
            name='nombre',
            field=models.CharField(max_length=200),
        ),
    ]
