# Generated by Django 5.2.7 on 2025-11-11 06:12

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('biblioteca', '0005_alter_alumno_nombre'),
    ]

    operations = [
        migrations.AddField(
            model_name='libro',
            name='status',
            field=models.CharField(choices=[('DISPONIBLE', 'Disponible'), ('PRESTADO', 'Prestado'), ('RESERVADO', 'Reservado'), ('PERDIDO', 'Perdido')], default='DISPONIBLE', max_length=12),
        ),
        migrations.AlterField(
            model_name='alumno',
            name='id_alumno',
            field=models.CharField(max_length=5, primary_key=True, serialize=False, validators=[django.core.validators.RegexValidator('^[A-Z0-9]+$', 'Solo se permiten letras mayúsculas y números.')]),
        ),
        migrations.AlterField(
            model_name='alumno',
            name='nombre',
            field=models.CharField(max_length=35),
        ),
        migrations.AlterField(
            model_name='autor',
            name='id_autor',
            field=models.CharField(max_length=5, primary_key=True, serialize=False, validators=[django.core.validators.RegexValidator('^[A-Z0-9]+$', 'Solo se permiten letras mayúsculas y números.')]),
        ),
        migrations.AlterField(
            model_name='carrera',
            name='id_carrera',
            field=models.CharField(max_length=5, primary_key=True, serialize=False, validators=[django.core.validators.RegexValidator('^[A-Z0-9]+$', 'Solo se permiten letras mayúsculas y números.')]),
        ),
        migrations.AlterField(
            model_name='categoria',
            name='id_categoria',
            field=models.CharField(max_length=5, primary_key=True, serialize=False, validators=[django.core.validators.RegexValidator('^[A-Z0-9]+$', 'Solo se permiten letras mayúsculas y números.')]),
        ),
        migrations.AlterField(
            model_name='editorial',
            name='id_editorial',
            field=models.CharField(max_length=5, primary_key=True, serialize=False, validators=[django.core.validators.RegexValidator('^[A-Z0-9]+$', 'Solo se permiten letras mayúsculas y números.')]),
        ),
        migrations.AlterField(
            model_name='historial',
            name='id_historial',
            field=models.CharField(max_length=5, primary_key=True, serialize=False, validators=[django.core.validators.RegexValidator('^[A-Z0-9]+$', 'Solo se permiten letras mayúsculas y números.')]),
        ),
        migrations.AlterField(
            model_name='libro',
            name='id_libro',
            field=models.CharField(max_length=5, primary_key=True, serialize=False, validators=[django.core.validators.RegexValidator('^[A-Z0-9]+$', 'Solo se permiten letras mayúsculas y números.')]),
        ),
        migrations.AlterField(
            model_name='prestamo',
            name='id_prestamo',
            field=models.CharField(max_length=5, primary_key=True, serialize=False, validators=[django.core.validators.RegexValidator('^[A-Z0-9]+$', 'Solo se permiten letras mayúsculas y números.')]),
        ),
        migrations.AlterField(
            model_name='sancion',
            name='id_sancion',
            field=models.CharField(max_length=5, primary_key=True, serialize=False, validators=[django.core.validators.RegexValidator('^[A-Z0-9]+$', 'Solo se permiten letras mayúsculas y números.')]),
        ),
        migrations.AlterField(
            model_name='usuario',
            name='id_usuario',
            field=models.CharField(max_length=5, primary_key=True, serialize=False, validators=[django.core.validators.RegexValidator('^[A-Z0-9]+$', 'Solo se permiten letras mayúsculas y números.')]),
        ),
    ]
